// JSON-LD structured data uses dangerouslySetInnerHTML per Next.js convention.
export const blogPageTemplate = [
  'import { blog } from "@/lib/blog";',
  'import { BlogGrid } from "@strategicnerds/nerds-mdx-blog/components";',
  'import { generateCollectionJsonLd } from "@strategicnerds/nerds-mdx-blog";',
  "",
  "export const revalidate = 86400;",
  "",
  "export const metadata = {",
  "  title: blog.config.blog.title,",
  "  description: blog.config.blog.description,",
  "};",
  "",
  "export default async function BlogPage() {",
  "  const posts = blog.getAllPosts();",
  "  const jsonLd = generateCollectionJsonLd(posts.slice(0, 20), blog.config);",
  "",
  "  return (",
  '    <div className="bg-white min-h-screen">',
  "      <script",
  '        type="application/ld+json"',
  "        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}",
  "      />",
  "      {/* Hero header */}",
  '      <div className="bg-slate-50 border-b border-slate-200">',
  '        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24">',
  '          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-slate-900">',
  "            {blog.config.blog.title}",
  "          </h1>",
  "          {blog.config.blog.description && (",
  '            <p className="mt-4 text-lg sm:text-xl text-slate-600 max-w-2xl">',
  "              {blog.config.blog.description}",
  "            </p>",
  "          )}",
  "        </div>",
  "      </div>",
  "      {/* Post grid */}",
  '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">',
  "        <BlogGrid",
  "          initialPosts={posts}",
  "          postsPerPage={blog.config.blog.postsPerPage}",
  "          basePath={blog.config.blog.basePath}",
  "        />",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
].join("\n");
