// Template uses array.join to avoid nested template literal escaping issues.
// JSON-LD structured data uses dangerouslySetInnerHTML per Next.js convention.
export const blogSlugPageTemplate = [
  'import { notFound } from "next/navigation";',
  'import Image from "next/image";',
  'import Link from "next/link";',
  'import { MDXRemote } from "next-mdx-remote/rsc";',
  'import { blog } from "@/lib/blog";',
  "import {",
  "  getMdxComponents,",
  "  getRemarkPlugins,",
  "  getRehypePlugins,",
  "  generateArticleJsonLd,",
  "  generateBreadcrumbJsonLd,",
  "  generateFAQJsonLd,",
  "  generateHowToJsonLd,",
  "  formatTagName,",
  '} from "@strategicnerds/nerds-mdx-blog";',
  "import {",
  "  BlogContent,",
  "  TableOfContents,",
  "  RelatedPosts,",
  '} from "@strategicnerds/nerds-mdx-blog/components";',
  'import type { Metadata } from "next";',
  "",
  "type PageProps = {",
  "  params: Promise<{ slug: string }>;",
  "};",
  "",
  "export async function generateStaticParams() {",
  "  return blog.getAllPosts().map((post) => ({ slug: post.slug }));",
  "}",
  "",
  "export async function generateMetadata({ params }: PageProps): Promise<Metadata> {",
  "  const { slug } = await params;",
  "  const post = blog.getPostBySlug(slug);",
  '  if (!post) return { title: "Not found" };',
  "",
  "  const url = `${blog.config.siteUrl}${blog.config.blog.basePath}/${slug}`;",
  "  const description = post.description || post.excerpt;",
  "",
  "  return {",
  "    title: post.title,",
  "    description,",
  "    alternates: { canonical: url },",
  "    openGraph: {",
  "      title: post.title,",
  "      description,",
  '      type: "article",',
  "      publishedTime: post.publishedAt,",
  "      ...(post.updatedAt && { modifiedTime: post.updatedAt }),",
  "      ...(blog.config.author.name && { authors: [blog.config.author.name] }),",
  "      url,",
  "      images: post.featureImage ? [post.featureImage] : undefined,",
  "    },",
  "    twitter: {",
  '      card: "summary_large_image",',
  "      title: post.title,",
  "      description,",
  "      ...(blog.config.author.twitter && { creator: blog.config.author.twitter }),",
  "      images: post.featureImage ? [post.featureImage] : undefined,",
  "    },",
  "  };",
  "}",
  "",
  "export default async function BlogPostPage({ params }: PageProps) {",
  "  const { slug } = await params;",
  "  const post = blog.getPostBySlug(slug);",
  "  if (!post) notFound();",
  "",
  "  const relatedPosts = blog.getRelatedPosts(slug, 3);",
  "  const components = getMdxComponents();",
  "  const articleJsonLd = generateArticleJsonLd(post, blog.config);",
  "  const breadcrumbJsonLd = generateBreadcrumbJsonLd(post, blog.config);",
  "",
  "  return (",
  "    <>",
  "      <script",
  '        type="application/ld+json"',
  "        dangerouslySetInnerHTML={{",
  "          __html: JSON.stringify([articleJsonLd, breadcrumbJsonLd]),",
  "        }}",
  "      />",
  "      {post.faqs && (",
  "        <script",
  '          type="application/ld+json"',
  "          dangerouslySetInnerHTML={{",
  "            __html: JSON.stringify(generateFAQJsonLd(post.faqs)),",
  "          }}",
  "        />",
  "      )}",
  "      {post.howToSteps && (",
  "        <script",
  '          type="application/ld+json"',
  "          dangerouslySetInnerHTML={{",
  "            __html: JSON.stringify(",
  "              generateHowToJsonLd(post, post.howToSteps, blog.config)",
  "            ),",
  "          }}",
  "        />",
  "      )}",
  "",
  '      <article className="min-h-screen">',
  '        <header className="border-b" style={{ borderColor: "var(--border)" }}>',
  '          <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">',
  '            <div className="flex items-center gap-3 text-sm" style={{ color: "var(--muted-foreground)" }}>',
  "              <Link",
  "                href={blog.config.blog.basePath}",
  '                className="hover:underline"',
  '                style={{ color: "var(--primary)" }}',
  "              >",
  "                {blog.config.blog.title}",
  "              </Link>",
  '              <span className="opacity-40">/</span>',
  "              <time dateTime={post.publishedAt}>",
  '                {new Date(post.publishedAt).toLocaleDateString("en-US", {',
  '                  year: "numeric",',
  '                  month: "long",',
  '                  day: "numeric",',
  "                })}",
  "              </time>",
  "              {post.readingTime && (",
  "                <>",
  '                  <span className="opacity-40">\\u00b7</span>',
  "                  <span>{post.readingTime} min read</span>",
  "                </>",
  "              )}",
  "            </div>",
  '            <h1 className="mt-6 text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight leading-tight" style={{ color: "var(--foreground)" }}>',
  "              {post.title}",
  "            </h1>",
  '            <p className="mt-6 text-lg sm:text-xl leading-relaxed" style={{ color: "var(--muted-foreground)" }}>',
  "              {post.excerpt}",
  "            </p>",
  "            {post.tags && post.tags.length > 0 && (",
  '              <div className="mt-6 flex flex-wrap gap-2">',
  "                {post.tags.map((tag) => (",
  "                  <Link",
  "                    key={tag}",
  "                    href={`${blog.config.blog.basePath}/tag/${encodeURIComponent(tag)}`}",
  '                    className="px-3 py-1 text-sm rounded-full transition-all duration-150"',
  "                    style={{",
  '                      backgroundColor: "var(--accent)",',
  '                      color: "var(--accent-foreground)",',
  "                    }}",
  "                  >",
  "                    {formatTagName(tag, blog.config.tagAcronyms)}",
  "                  </Link>",
  "                ))}",
  "              </div>",
  "            )}",
  "          </div>",
  "        </header>",
  "",
  "        {post.featureImage && (",
  '          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 -mb-8 relative z-10" style={{ marginTop: "-2rem" }}>',
  '            <div className="relative aspect-[2/1] rounded-2xl overflow-hidden shadow-2xl">',
  "              <Image",
  "                src={post.featureImage}",
  "                alt={post.title}",
  "                fill",
  '                className="object-cover"',
  "                priority",
  '                sizes="(max-width: 1200px) 100vw, 1200px"',
  "              />",
  "            </div>",
  "          </div>",
  "        )}",
  "",
  '        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">',
  "          <TableOfContents content={post.content} />",
  "",
  "          <BlogContent>",
  '            <div className="prose prose-lg max-w-none',
  "              prose-headings:font-semibold prose-headings:tracking-tight",
  "              prose-p:leading-relaxed",
  "              prose-a:font-medium prose-a:no-underline hover:prose-a:underline",
  "              prose-img:rounded-xl prose-img:shadow-lg",
  "              prose-pre:rounded-xl prose-pre:shadow-lg",
  "              prose-blockquote:border-l-[3px] prose-blockquote:not-italic prose-blockquote:font-normal",
  '              prose-code:before:content-none prose-code:after:content-none"',
  "              style={{",
  '                "--tw-prose-links": "var(--primary)",',
  '                "--tw-prose-headings": "var(--foreground)",',
  '                "--tw-prose-body": "var(--foreground)",',
  '                "--tw-prose-bold": "var(--foreground)",',
  '                "--tw-prose-quotes": "var(--muted-foreground)",',
  '                "--tw-prose-quote-borders": "var(--primary)",',
  '                "--tw-prose-code": "var(--foreground)",',
  '                "--tw-prose-hr": "var(--border)",',
  "              } as React.CSSProperties}",
  "            >",
  "              <MDXRemote",
  "                source={post.content}",
  "                components={components}",
  "                options={{",
  "                  mdxOptions: {",
  "                    remarkPlugins: getRemarkPlugins(),",
  "                    rehypePlugins: getRehypePlugins() as never,",
  "                  },",
  "                }}",
  "              />",
  "            </div>",
  "          </BlogContent>",
  "",
  "          <RelatedPosts",
  "            posts={relatedPosts}",
  "            currentSlug={slug}",
  "            basePath={blog.config.blog.basePath}",
  "          />",
  "        </div>",
  "      </article>",
  "    </>",
  "  );",
  "}",
  "",
].join("\n");
