// Template uses array.join to avoid nested template literal escaping issues.
// JSON-LD structured data uses dangerouslySetInnerHTML per Next.js convention.
export const blogSlugPageTemplate = [
  'import { notFound } from "next/navigation";',
  'import Image from "next/image";',
  'import Link from "next/link";',
  'import { MDXRemote } from "next-mdx-remote/rsc";',
  'import { blog } from "@/lib/blog";',
  "import {",
  "  getMdxComponents,",
  "  getRemarkPlugins,",
  "  getRehypePlugins,",
  "  generateArticleJsonLd,",
  "  generateBreadcrumbJsonLd,",
  "  generateFAQJsonLd,",
  "  generateHowToJsonLd,",
  "  formatTagName,",
  '} from "@strategicnerds/nerds-mdx-blog";',
  "import {",
  "  BlogContent,",
  "  TableOfContents,",
  "  RelatedPosts,",
  '} from "@strategicnerds/nerds-mdx-blog/components";',
  'import type { Metadata } from "next";',
  "",
  "type PageProps = {",
  "  params: Promise<{ slug: string }>;",
  "};",
  "",
  "export async function generateStaticParams() {",
  "  return blog.getAllPosts().map((post) => ({ slug: post.slug }));",
  "}",
  "",
  "export async function generateMetadata({ params }: PageProps): Promise<Metadata> {",
  "  const { slug } = await params;",
  "  const post = blog.getPostBySlug(slug);",
  '  if (!post) return { title: "Not found" };',
  "",
  "  const url = `${blog.config.siteUrl}${blog.config.blog.basePath}/${slug}`;",
  "  const description = post.description || post.excerpt;",
  "",
  "  return {",
  "    title: post.title,",
  "    description,",
  "    alternates: { canonical: url },",
  "    openGraph: {",
  "      title: post.title,",
  "      description,",
  '      type: "article",',
  "      publishedTime: post.publishedAt,",
  "      ...(post.updatedAt && { modifiedTime: post.updatedAt }),",
  "      ...(blog.config.author.name && { authors: [blog.config.author.name] }),",
  "      url,",
  "      images: post.featureImage ? [post.featureImage] : undefined,",
  "    },",
  "    twitter: {",
  '      card: "summary_large_image",',
  "      title: post.title,",
  "      description,",
  "      ...(blog.config.author.twitter && { creator: blog.config.author.twitter }),",
  "      images: post.featureImage ? [post.featureImage] : undefined,",
  "    },",
  "  };",
  "}",
  "",
  "export default async function BlogPostPage({ params }: PageProps) {",
  "  const { slug } = await params;",
  "  const post = blog.getPostBySlug(slug);",
  "  if (!post) notFound();",
  "",
  "  const relatedPosts = blog.getRelatedPosts(slug, 3);",
  "  const components = getMdxComponents();",
  "  const articleJsonLd = generateArticleJsonLd(post, blog.config);",
  "  const breadcrumbJsonLd = generateBreadcrumbJsonLd(post, blog.config);",
  "",
  "  return (",
  "    <>",
  "      <script",
  '        type="application/ld+json"',
  "        dangerouslySetInnerHTML={{",
  "          __html: JSON.stringify([articleJsonLd, breadcrumbJsonLd]),",
  "        }}",
  "      />",
  "      {post.faqs && (",
  "        <script",
  '          type="application/ld+json"',
  "          dangerouslySetInnerHTML={{",
  "            __html: JSON.stringify(generateFAQJsonLd(post.faqs)),",
  "          }}",
  "        />",
  "      )}",
  "      {post.howToSteps && (",
  "        <script",
  '          type="application/ld+json"',
  "          dangerouslySetInnerHTML={{",
  "            __html: JSON.stringify(",
  "              generateHowToJsonLd(post, post.howToSteps, blog.config)",
  "            ),",
  "          }}",
  "        />",
  "      )}",
  "",
  '      <article className="bg-white min-h-screen text-slate-900 font-sans text-base antialiased">',
  "        {/* Header */}",
  '        <header className="border-b border-slate-200 bg-slate-50">',
  '          <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">',
  '            <div className="flex items-center gap-3 text-sm text-slate-500">',
  "              <Link",
  "                href={blog.config.blog.basePath}",
  '                className="text-indigo-600 hover:text-indigo-700 hover:underline font-medium"',
  "              >",
  "                {blog.config.blog.title}",
  "              </Link>",
  '              <span className="text-slate-300">/</span>',
  "              <time dateTime={post.publishedAt}>",
  '                {new Date(post.publishedAt).toLocaleDateString("en-US", {',
  '                  year: "numeric",',
  '                  month: "long",',
  '                  day: "numeric",',
  "                })}",
  "              </time>",
  "              {post.readingTime && (",
  "                <>",
  '                  <span className="text-slate-300">{\"\\u00b7\"}</span>',
  "                  <span>{post.readingTime} min read</span>",
  "                </>",
  "              )}",
  "            </div>",
  '            <h1 className="mt-6 text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight leading-tight text-slate-900">',
  "              {post.title}",
  "            </h1>",
  '            <p className="mt-6 text-lg sm:text-xl leading-relaxed text-slate-600">',
  "              {post.excerpt}",
  "            </p>",
  "            {post.tags && post.tags.length > 0 && (",
  '              <div className="mt-6 flex flex-wrap gap-2">',
  "                {post.tags.map((tag) => (",
  "                  <Link",
  "                    key={tag}",
  "                    href={`${blog.config.blog.basePath}/tag/${encodeURIComponent(tag)}`}",
  '                    className="px-3 py-1 text-sm rounded-full bg-indigo-50 text-indigo-700 hover:bg-indigo-100 transition-colors"',
  "                  >",
  "                    {formatTagName(tag, blog.config.tagAcronyms)}",
  "                  </Link>",
  "                ))}",
  "              </div>",
  "            )}",
  "          </div>",
  "        </header>",
  "",
  "        {/* Feature image */}",
  "        {post.featureImage && (",
  '          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 -mt-8 relative z-10">',
  '            <div className="relative aspect-[2/1] rounded-2xl overflow-hidden shadow-2xl ring-1 ring-slate-900/5">',
  "              <Image",
  "                src={post.featureImage}",
  "                alt={post.title}",
  "                fill",
  '                className="object-cover"',
  "                priority",
  '                sizes="(max-width: 1200px) 100vw, 1200px"',
  "              />",
  "            </div>",
  "          </div>",
  "        )}",
  "",
  "        {/* Content */}",
  '        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">',
  "          <TableOfContents content={post.content} />",
  "",
  "          <BlogContent>",
  '            <div className="prose prose-lg prose-slate max-w-none',
  "              prose-headings:font-semibold prose-headings:tracking-tight prose-headings:text-slate-900",
  "              prose-p:text-slate-700 prose-p:leading-relaxed",
  "              prose-a:text-indigo-600 prose-a:font-medium prose-a:no-underline hover:prose-a:underline",
  "              prose-strong:text-slate-900",
  "              prose-img:rounded-xl prose-img:shadow-lg",
  "              prose-pre:rounded-xl prose-pre:shadow-lg prose-pre:bg-slate-900",
  "              prose-blockquote:border-l-[3px] prose-blockquote:border-indigo-500 prose-blockquote:not-italic prose-blockquote:text-slate-600",
  '              prose-code:before:content-none prose-code:after:content-none prose-code:text-indigo-700 prose-code:bg-indigo-50 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:text-sm prose-code:font-medium"',
  "            >",
  "              <MDXRemote",
  "                source={post.content}",
  "                components={components}",
  "                options={{",
  "                  mdxOptions: {",
  "                    remarkPlugins: getRemarkPlugins(),",
  "                    rehypePlugins: getRehypePlugins() as never,",
  "                  },",
  "                }}",
  "              />",
  "            </div>",
  "          </BlogContent>",
  "",
  "          <RelatedPosts",
  "            posts={relatedPosts}",
  "            currentSlug={slug}",
  "            basePath={blog.config.blog.basePath}",
  "          />",
  "        </div>",
  "      </article>",
  "    </>",
  "  );",
  "}",
  "",
].join("\n");
