// JSON-LD structured data uses dangerouslySetInnerHTML per Next.js convention.
// The data is generated server-side from trusted config, not user input.
export const blogPageTemplate = [
  'import { blog } from "@/lib/blog";',
  'import { BlogGrid } from "@strategicnerds/nerds-mdx-blog/components";',
  'import { generateCollectionJsonLd } from "@strategicnerds/nerds-mdx-blog";',
  "",
  "export const revalidate = 86400;",
  "",
  "export const metadata = {",
  "  title: blog.config.blog.title,",
  "  description: blog.config.blog.description,",
  "};",
  "",
  "export default async function BlogPage() {",
  "  const posts = blog.getAllPosts();",
  "  const jsonLd = generateCollectionJsonLd(posts.slice(0, 20), blog.config);",
  "",
  "  return (",
  "    <>",
  "      <script",
  '        type="application/ld+json"',
  "        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}",
  "      />",
  '      <div className="border-b border-[var(--border)]">',
  '        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24">',
  '          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight" style={{ color: "var(--foreground)" }}>',
  "            {blog.config.blog.title}",
  "          </h1>",
  "          {blog.config.blog.description && (",
  '            <p className="mt-4 text-lg sm:text-xl max-w-2xl" style={{ color: "var(--muted-foreground)" }}>',
  "              {blog.config.blog.description}",
  "            </p>",
  "          )}",
  "        </div>",
  "      </div>",
  '      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">',
  "        <BlogGrid",
  "          initialPosts={posts}",
  "          postsPerPage={blog.config.blog.postsPerPage}",
  "          basePath={blog.config.blog.basePath}",
  "        />",
  "      </div>",
  "    </>",
  "  );",
  "}",
  "",
].join("\n");
