"use client";

import { useEffect, useRef, useState } from "react";

type MermaidProps = {
  readonly chart: string;
  readonly className?: string;
};

// SVG output from mermaid.render() is safe -- it's generated by the
// mermaid library from a declarative chart DSL, not from user HTML input.
export function Mermaid({ chart, className = "" }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");

  useEffect(() => {
    let cancelled = false;

    async function render() {
      const mermaid = (await import("mermaid")).default;
      mermaid.initialize({
        startOnLoad: false,
        theme: "base",
        themeVariables: {
          primaryColor: "#1f2937",
          primaryTextColor: "#f9fafb",
          primaryBorderColor: "#4b5563",
          lineColor: "#e5e7eb",
          secondaryColor: "#111827",
          tertiaryColor: "#111827",
          background: "transparent",
          mainBkg: "#1f2937",
          nodeBorder: "#4b5563",
          clusterBkg: "#111827",
          titleColor: "#f9fafb",
          edgeLabelBackground: "#0a0a0f",
          nodeTextColor: "#f9fafb",
          fontSize: "16px",
          fontFamily:
            "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        },
        flowchart: {
          htmlLabels: true,
          curve: "basis",
          padding: 24,
          nodeSpacing: 70,
          rankSpacing: 90,
          diagramPadding: 32,
          useMaxWidth: true,
        },
      });

      const id = `mermaid-${Math.random().toString(36).slice(2, 9)}`;
      const { svg: rendered } = await mermaid.render(id, chart.trim());

      if (!cancelled) {
        setSvg(rendered);
      }
    }

    render();
    return () => {
      cancelled = true;
    };
  }, [chart]);

  return (
    <div
      ref={containerRef}
      className={`my-8 flex justify-center overflow-x-auto rounded-xl border border-border bg-gray-950 p-8 [&_svg]:max-w-full [&_.edgeLabel]:text-sm [&_.edgeLabel]:text-gray-300 ${className}`}
      dangerouslySetInnerHTML={svg ? { __html: svg } : undefined}
    />
  );
}
